- name: Test Scale in
  aws_emr:
    aws_access_key: "{{ AWS_ACCESS_KEY }}"
    aws_secret_key: "{{ AWS_SECURITY_KEY }}"
    region: "{{ AWS_REGION }}"
    mode: scale-in
    id: "{{ CLUSTER_ID }}"
    scale_in_instance_out: 1
  register: result

- debug:
    msg: "{{ result }}"
